spring:
  config:
    import: optional:import:file.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_currency_bot
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
bot:
  name: CryptoCurrencyBotInnowise_bot
  token: 6843903534:AAHIkwZUF_RxbnAxfZXaT5yyAdp4VSmsiow
currency-api:
  url: https://api.mexc.com/api/v3/ticker/price
